# Simple CD workflow to deploy to my personal server
# This workflow is triggered on push to deployed-blog branch

name: Deploy blog to server

on:
  push:
    branches: [deployed-blog]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd svelte-markdown/
            git pull origin main
            git status
            npm install
            npm run build
            pm2 restart blog
